#pragma once
#include "CoreMinimal.h"
#include "ECrabLesserProjectileType.generated.h"

UENUM(BlueprintType)
enum class ECrabLesserProjectileType : uint8 {
    None,
    Duplicate,
    Generic,
    TimeBolt,
    UltraShot,
    ReloadArc,
    LinkShot,
    DrillShot,
    BubbleShot,
    PumpkinShot,
    DaggerArc,
    PiercingWave,
    ArcaneBlast,
    ShotgunBlast,
    MaceShot,
    FireworkShot,
    ThornShot,
    SparkShot,
    ProximityBarrage,
    HomingBlade,
    BombShot,
    TorpedoShot,
    FireballShot,
    SharpenedAxe,
    TriangleShot,
    BeamShot,
    BubbleBlast,
    DaggerBlast,
    FireworkExplosion,
    ThornExplosion,
    SparkExplosion,
    SentryTurret,
    SniperTurret,
    CloneExplosion,
    BombExplosion,
    SpinningBlade,
    MortarTurret,
    WaveTurret,
    BeamTurret,
    OrbitingScythe,
    DaggerDash,
};

