#pragma once
#include "CoreMinimal.h"
#include "ECrabAbilityModType.generated.h"

UENUM(BlueprintType)
enum class ECrabAbilityModType : uint8 {
    None,
    LightExplosion,
    GlueExplosion,
    ChaoticExplosion,
    BigAbility,
    IronExplosion,
    TimeExplosion,
    ImplodingExplosion,
    BiggerBoom,
    WeakExplosion,
    SlowExplosion,
    HeatSink,
    BouncingExplosion,
    DamageExplosion,
    TripleAbility,
    LayeredExplosion,
    AuraExplosion,
    BubbleBlast,
    DaggerBlast,
    FireworkExplosion,
    ThornExplosion,
    SparkExplosion,
    ShrapnelExplosion,
    BarrelExplosion,
    LandmineExplosion,
    ElementalExplosion,
    PopcornExplosion,
    GiantDrill,
    LightningBeam,
    PoisonVines,
    ToxicCloud,
    ArcaneRift,
    ArtilleryStrike,
    TurretExplosion,
    SentryTurret,
    SniperTurret,
    Grenadier,
    DamagingCast,
    HealingCast,
    SplitAbility,
    TargetingExplosion,
    CloneExplosion,
    BombExplosion,
    SpinningBlade,
    SporeExplosion,
    UltraMushroom,
    ScytheVortex,
    CrystalBarrage,
    EnergyRing,
    MOAB,
    StarfishExplosion,
    IceExplosion,
    FireExplosion,
    LightningExplosion,
    PoisonExplosion,
    SpikeStrike,
    CrystalStrike,
    MortarTurret,
    WaveTurret,
    BeamTurret,
};

